kind: pipeline
name: ARM64 Tests

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: gcc:10
    commands:
      - sudo apt-get install cmake
      - cmake -B build/
      - cd build && make -j3 && ctest