kind: pipeline
name: ARM64 Tests

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: gcc:10
    commands:
      - wget -q https://github.com/Kitware/CMake/releases/download/v3.19.6/cmake-3.19.6-Linux-aarch64.tar.gz -O cmake.tar.gz
      - mkdir cmake-bin
      - tar xvf cmake.tar.gz --strip 1 -C cmake-bin
      - ls -R .
      - export PATH=`pwd`/cmake-bin/bin:$PATH
      - cmake -B build/
      - cd build && make -j3 && ctest